/**
 * Returns a copy of Array a where in between the elements of 'a' there 
 * are padding elements generated by the function (that accepts the 
 * index of the padding element)
 * @param {array} a 
 * @param {function} f 
 * @returns An Array like 'a' but with elements in between elements of A
 */
 export function padArray(a, f) {
    for (let i = 0; 2*i < a.length-1; i++) {
        a.splice(2*i+1, 0, f(2*i+1));
    }
    return a;
}